# Generated by Django 5.1.5 on 2025-01-30 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Base_App', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booktable',
            old_name='Booking_date',
            new_name='booking_date',
        ),
        migrations.RenameField(
            model_name='booktable',
            old_name='Email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='booktable',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='booktable',
            old_name='Phone_number',
            new_name='phone_number',
        ),
        migrations.RenameField(
            model_name='booktable',
            old_name='Total_person',
            new_name='total_person',
        ),
    ]
