# Generated by Django 5.1.5 on 2025-02-03 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base_App', '0005_order_status_order_upi_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('received', 'Order Received'), ('preparing', 'Preparing'), ('on_the_way', 'On the Way'), ('delivered', 'Delivered')], default='received', max_length=50),
        ),
    ]
